# Disable the comments of the coverage
comment: off

# Configuration, requiring, at least, a 90% of coverage
coverage:
  status:
    project:
      default:
        target: 90
    patch:
      default:
        target: 90
