# Make it explicit that we favor the
# new container-based travis workers
language: python

# Cache to speed-up the build process
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

# Run the CI in a Linux environment running Ubuntu Xenial 16.04.3
dist: xenial

# Enviromental variables
env:
  global:
    - TEST_DIR=/tmp/sklr

# Specify the build matrix
matrix:
  include:
    # Linux environment to test scikit-lr against NumPy and
    # SciPy installed from their CI wheels in a virtualenv
    # with the Python interpreter provided by Travis.
    # In fact, the testing is carried out with the latest
    # versions of the packages since, during the development
    # process, the minimum required versions will be employed
    -  python: 3.7
       env: COVERAGE="true"

# Install the packages
install: source build_tools/travis/install.sh

# Execute the tests
script: bash build_tools/travis/script.sh

# Run post-test steps
after_success: bash build_tools/travis/after_success.sh
