# Make it explicit that we favor the new container-based travis workers
language: python

# Cache to speedup the build process
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

# Set the Linux environment to Ubuntu Xenial 16.04
dist: xenial

# Enviromental variables
env:
  global:
    - TEST_DIR=/tmp/plr

# Specify in the build matrix
matrix:
  include:
    # Linux environment to test plr against NumPy and SciPy
    # installed from their CI wheels in a virtualenv with
    # the Python interpreter provided by Travis
    -  python: 3.7
       env: COVERAGE="true"

# Install the packages
install: source build_tools/travis/install.sh

# Execute the tests
script: bash build_tools/travis/script.sh

# Run post-test steps
after_success: bash build_tools/travis/after_success.sh
