# Minimum build system requirements
[build-system]
requires = ["setuptools",
            "wheel",
            "numpy>=1.17.3",
            "scipy>=1.3.2",
            "cython>=0.29.14",
            "scikit-learn>=1.2.0",
            "pandas>=2.1"]
